### ISSUE TITLE
[Epic] Push SDK

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/push-client-js#1]
## Resources

- [Push Dapp Client API](https://docs.walletconnect.com/2.0/specs/clients/push/dapp-client-api)
- [Push Wallet Client API](https://docs.walletconnect.com/2.0/specs/clients/push/wallet-client-api)

## Implementation Path

This is intended as an overview of critical path work for the Push SDK, from which we can break out concrete and more detailed individual issues. The list may change and reorder as we see necessary during the development process.

### SDK Client

- [x] Pull in `@walletconnect/core`
- [x] Set up logging
- [x] Set up PushEngine
- [x] Specify RPC method types
- [x] Set up relayer events handling
- [x] Set up common `BaseClient` class
- [x] Set up `DappClient` class
- [x] Set up `WalletClient` class
- [x] Set up test harness
- [x] Implement top-level event handlers (`on("push_request",...)`, `on("push_response",...)`
- [x] Storage handling and storage key namespacing via `Core.Store` 
	- [x] `requests` store
	- [x] `subscriptions` store
	- [x] Ensure restoring from persistence works as expected, specify `getKey` for each store if necessary.
- [x] **Milestone 1**: Dapp and Wallet exchange keys over an existing pairing to create the topic for the push to send messages
- [x] Dapp can issue a push_message over the agreed push topic. Wallet is able to receive and process the incoming push_message
- [x] Implement getters (`getActiveSubscriptions`)
- [x] Implement `delete`
- [x] Implement `wallet.reject`
- [x] Implement `wc_pushDelete` RPC method + `on("push_delete")` handler
- [x] Implement `wallet.decryptMessage`
- [x] Implement metadata
- [x] Clean up remaining types
- [x] Use error codes spec'd in https://docs.walletconnect.com/2.0/specs/clients/push/error-codes
- [x] Write first docs iteration: https://github.com/WalletConnect/walletconnect-docs/pull/399
- [x] Implement expirer logic for requests
- [x] Align with spec follow-up changes:
	- [x] https://github.com/WalletConnect/walletconnect-docs/commit/b35980b08fe899627d593f60eca9a4ed54ec249a
	- [x] https://github.com/WalletConnect/walletconnect-docs/pull/416
- [x]  #3 

### Next steps

- #9 

### Background service + React Native

Depends on:
- https://github.com/WalletConnect/WalletConnectKotlinV2/issues/500
- https://github.com/WalletConnect/WalletConnectSwiftV2/issues/606

See: 
- #7
