### ISSUE TITLE
[Epic] Milestone 2: Account Discoverability Flows

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/push-client-js#9]
## Context

- See spec: https://github.com/WalletConnect/walletconnect-docs/pull/574

### `wc_pushSubscribe`

- [x] Set up `public subscribe(params: { metadata: Metadata, account: string, onSign: (message: string) => Cacao.Signature }): Promise<boolean>;` method
- [x] Implement `onPushSubscribeResponse` to handle the Cast server response on subscribe topic (created push subscription or error)
- [x] Implement integration test for `wc_pushSubscribe` flow
- [x] Expand subscriptionAuth JWT with `scp` (scope) parameter: https://github.com/WalletConnect/walletconnect-docs/pull/574/files#diff-4bd6ce081dc59b425d0e543b5e879e47600c3472fcd9a61674b46ad5134d0d1bR25

### `wc_pushUpdate`

- Branch: https://github.com/WalletConnect/push-client-js/tree/feat/push-update-2
- [x] Set up `public update(params: { topic: string, scope: string[] }): Promise<boolean>;` method
- [x] Implement `onPushUpdateResponse` to handle the Cast server response on push topic (updated push subscription or error)
- [x] Implement integration test for `wc_pushUpdate` flow
